[[theme.fontFaces]]
family = "Times"
url = "app/static/times.ttf"
style = "normal"
weight = "200"

[theme]
base="dark"
primaryColor = "#1ed760"
backgroundColor = "#2a2a2a"
secondaryBackgroundColor = "#121212"
codeBackgroundColor = "#121212"
font = 'Times'